# Python 基础语法

In [2]:
a = ['a','b','c','d','e']
print(a, type(a))

['a', 'b', 'c', 'd', 'e'] <class 'list'>


In [3]:
#增删改查
a.append('ddd')
print(a)
print(a[4])

['a', 'b', 'c', 'd', 'e', 'ddd']
e


In [13]:
d = {1:'a',2:'b',3:'c','d':'apple'} 
d[4] = 55
d['W1'] = 10
net = {'W1'}
print(d['W1'])

10


In [14]:
a = 20
if a<3:
    print("小于3")
elif a>10:
    print("大于10")
else:
    print("执行代码")

大于10


In [15]:
a = ['a','b','c']
for item in a :
    print(item)

a
b
c


In [16]:
a = 10
while a < 15:
    a = a+1
    print(a)

11
12
13
14
15


In [17]:
def hello(name):
    print("Hello ", name, "!")
hello('print')

Hello  print !


In [18]:
def add(x):
    y = x + 10
    return y
z = add(5)
print(z)

15


In [19]:
class Mankind:
    def __init__(self, height, weight):
        self.height = height
        self.weight = weight
    
    def eat(self):
        print("我正在吃饭",self.weight)

jack = Mankind(182, 82)
tom = Mankind(180, 72)
jack.eat()
print(jack.height, jack.weight)

我正在吃饭 82
182 82


# Numpy 基础入法

In [20]:
import numpy as np
#numpy是一个外部库
"""
需要import来导入
"""

'\n需要import来导入\n'

In [21]:
#numpy的数组的定义
x = np.array([1.0,2.0,3.0,1])
print(x)

[1. 2. 3. 1.]


In [22]:
#算术运算 
x = np.array([1.1, 10.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(type(x + y))
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)

<class 'numpy.ndarray'>
[-0.9  6.  -3. ]
[ 2.2 40.  18. ]
[0.55 2.5  0.5 ]
[0. 2. 0.]
[1.1 2.  3. ]


In [23]:
#多维数组
x = np.array([[1.0, 2.0], [3.0, 4.0]])
print(x[0][0])

1.0


In [24]:
#转置
x = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print(x)
print(x.T)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1. 3. 5.]
 [2. 4. 6.]]


In [26]:
y = np.array([[1.0, 2.0]])
#broadcasting广播
print(x * y)

[[ 1.  4.]
 [ 3.  8.]
 [ 5. 12.]]


In [28]:
#dot
print(x)
print(y)
z = np.dot(x,y.T) 
print(z)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1. 2.]]
[[ 5.]
 [11.]
 [17.]]


In [29]:
#增删改查
#插入：
x = np.array([[1.0, 2.0], [3.0, 4.0]])
x_add = np.array([[5.0, 6.0],[7.0, 8.0]])
print(x)
x = np.insert(x,0,x_add,axis=1)
print(x)

[[1. 2.]
 [3. 4.]]
[[5. 7. 1. 2.]
 [6. 8. 3. 4.]]


In [30]:
x = np.array([[1.0, 2.0], [3.0, 4.0]])
print(x)
x = np.append(x, x_add, axis=1)
print(x)

[[1. 2.]
 [3. 4.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [31]:
#删除
print(x)
x = np.delete(x, 0, axis=0)
print(x)

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
[[3. 4. 7. 8.]]


In [32]:
x = np.array([[1., 2], [3, 4]])
x[0][0] = 7
print(x)

[[7. 2.]
 [3. 4.]]
